# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import app.codegen.user_service_pb2 as user__service__pb2


class UserStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Create = channel.unary_unary(
        '/User.User/Create',
        request_serializer=user__service__pb2.NewUser.SerializeToString,
        response_deserializer=user__service__pb2.CreateUserResponse.FromString,
        )
    self.Delete = channel.unary_unary(
        '/User.User/Delete',
        request_serializer=user__service__pb2.DeleteUserRequest.SerializeToString,
        response_deserializer=user__service__pb2.DeleteUserResponse.FromString,
        )
    self.GetUser = channel.unary_unary(
        '/User.User/GetUser',
        request_serializer=user__service__pb2.GetUserRequest.SerializeToString,
        response_deserializer=user__service__pb2.GetUserResponse.FromString,
        )


class UserServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Create(self, request, context):
    """Create user
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    """Update user (?)

    Delete user
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetUser(self, request, context):
    """Get user
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=user__service__pb2.NewUser.FromString,
          response_serializer=user__service__pb2.CreateUserResponse.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=user__service__pb2.DeleteUserRequest.FromString,
          response_serializer=user__service__pb2.DeleteUserResponse.SerializeToString,
      ),
      'GetUser': grpc.unary_unary_rpc_method_handler(
          servicer.GetUser,
          request_deserializer=user__service__pb2.GetUserRequest.FromString,
          response_serializer=user__service__pb2.GetUserResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'User.User', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
