// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_service.proto

package com.instagram_clone.image_service;

/**
 * Protobuf enum {@code Image.CreateImageErrorStatus}
 */
public enum CreateImageErrorStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CREATE_IMAGE_SERVER_ERROR = 0;</code>
   */
  CREATE_IMAGE_SERVER_ERROR(0),
  /**
   * <code>CONTENT_TOO_LONG = 1;</code>
   */
  CONTENT_TOO_LONG(1),
  /**
   * <code>CREATOR_NOT_FOUND = 2;</code>
   */
  CREATOR_NOT_FOUND(2),
  /**
   * <code>INVALID_DATA = 3;</code>
   */
  INVALID_DATA(3),
  /**
   * <code>CAPTION_TOO_LONG = 4;</code>
   */
  CAPTION_TOO_LONG(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CREATE_IMAGE_SERVER_ERROR = 0;</code>
   */
  public static final int CREATE_IMAGE_SERVER_ERROR_VALUE = 0;
  /**
   * <code>CONTENT_TOO_LONG = 1;</code>
   */
  public static final int CONTENT_TOO_LONG_VALUE = 1;
  /**
   * <code>CREATOR_NOT_FOUND = 2;</code>
   */
  public static final int CREATOR_NOT_FOUND_VALUE = 2;
  /**
   * <code>INVALID_DATA = 3;</code>
   */
  public static final int INVALID_DATA_VALUE = 3;
  /**
   * <code>CAPTION_TOO_LONG = 4;</code>
   */
  public static final int CAPTION_TOO_LONG_VALUE = 4;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CreateImageErrorStatus valueOf(int value) {
    return forNumber(value);
  }

  public static CreateImageErrorStatus forNumber(int value) {
    switch (value) {
      case 0: return CREATE_IMAGE_SERVER_ERROR;
      case 1: return CONTENT_TOO_LONG;
      case 2: return CREATOR_NOT_FOUND;
      case 3: return INVALID_DATA;
      case 4: return CAPTION_TOO_LONG;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CreateImageErrorStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CreateImageErrorStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CreateImageErrorStatus>() {
          public CreateImageErrorStatus findValueByNumber(int number) {
            return CreateImageErrorStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.instagram_clone.image_service.ImageService.getDescriptor().getEnumTypes().get(1);
  }

  private static final CreateImageErrorStatus[] VALUES = values();

  public static CreateImageErrorStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CreateImageErrorStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Image.CreateImageErrorStatus)
}

