// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_service.proto

package com.instagram_clone.image_service;

public interface DeleteImageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Image.DeleteImageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Image.DeleteImageStatus status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.Image.DeleteImageStatus status = 1;</code>
   */
  com.instagram_clone.image_service.DeleteImageStatus getStatus();
}
