// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_service.proto

package com.instagram_clone.image_service;

public interface GetImageDataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Image.GetImageDataRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string image_id = 1;</code>
   */
  java.lang.String getImageId();
  /**
   * <code>string image_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getImageIdBytes();
}
