// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_service.proto

package com.instagram_clone.image_service;

public interface GetImageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Image.GetImageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Image.Image image = 1;</code>
   */
  com.instagram_clone.image_service.Image getImage();
  /**
   * <code>.Image.Image image = 1;</code>
   */
  com.instagram_clone.image_service.ImageOrBuilder getImageOrBuilder();

  /**
   * <code>.Image.GetImageErrorStatus error = 2;</code>
   */
  int getErrorValue();
  /**
   * <code>.Image.GetImageErrorStatus error = 2;</code>
   */
  com.instagram_clone.image_service.GetImageErrorStatus getError();

  public com.instagram_clone.image_service.GetImageResponse.StatusCase getStatusCase();
}
