// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_service.proto

package com.instagram_clone.image_service;

public interface GetLikesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Image.GetLikesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string image_id = 1;</code>
   */
  java.lang.String getImageId();
  /**
   * <code>string image_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getImageIdBytes();

  /**
   * <code>int32 size = 2;</code>
   */
  int getSize();

  /**
   * <code>int32 page = 3;</code>
   */
  int getPage();
}
