// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_service.proto

package com.instagram_clone.image_service;

/**
 * Protobuf enum {@code Image.GetLikesErrorStatus}
 */
public enum GetLikesErrorStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>GET_LIKES_SERVER_ERROR = 0;</code>
   */
  GET_LIKES_SERVER_ERROR(0),
  /**
   * <code>GET_LIKES_IMAGE_NOT_FOUND = 1;</code>
   */
  GET_LIKES_IMAGE_NOT_FOUND(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>GET_LIKES_SERVER_ERROR = 0;</code>
   */
  public static final int GET_LIKES_SERVER_ERROR_VALUE = 0;
  /**
   * <code>GET_LIKES_IMAGE_NOT_FOUND = 1;</code>
   */
  public static final int GET_LIKES_IMAGE_NOT_FOUND_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static GetLikesErrorStatus valueOf(int value) {
    return forNumber(value);
  }

  public static GetLikesErrorStatus forNumber(int value) {
    switch (value) {
      case 0: return GET_LIKES_SERVER_ERROR;
      case 1: return GET_LIKES_IMAGE_NOT_FOUND;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GetLikesErrorStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      GetLikesErrorStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GetLikesErrorStatus>() {
          public GetLikesErrorStatus findValueByNumber(int number) {
            return GetLikesErrorStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.instagram_clone.image_service.ImageService.getDescriptor().getEnumTypes().get(6);
  }

  private static final GetLikesErrorStatus[] VALUES = values();

  public static GetLikesErrorStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private GetLikesErrorStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Image.GetLikesErrorStatus)
}

