// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_service.proto

package com.instagram_clone.image_service;

public interface ImageLikesPageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Image.ImageLikesPage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Image ID
   * </pre>
   *
   * <code>string image_id = 1;</code>
   */
  java.lang.String getImageId();
  /**
   * <pre>
   * Image ID
   * </pre>
   *
   * <code>string image_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getImageIdBytes();

  /**
   * <pre>
   * Page size (e.g. 20); guaranteed maximum of retrieved likes
   * </pre>
   *
   * <code>int32 size = 2;</code>
   */
  int getSize();

  /**
   * <pre>
   * Page number (e.g. 2)
   * </pre>
   *
   * <code>int32 page = 3;</code>
   */
  int getPage();

  /**
   * <pre>
   * User count in this page
   * </pre>
   *
   * <code>int32 users_count = 4;</code>
   */
  int getUsersCount4();

  /**
   * <pre>
   * Total user count
   * </pre>
   *
   * <code>int32 total_users_count = 5;</code>
   */
  int getTotalUsersCount();

  /**
   * <pre>
   * Array of user IDs who have liked the image
   * </pre>
   *
   * <code>repeated string users = 6;</code>
   */
  java.util.List<java.lang.String>
      getUsers6List();
  /**
   * <pre>
   * Array of user IDs who have liked the image
   * </pre>
   *
   * <code>repeated string users = 6;</code>
   */
  int getUsers6Count();
  /**
   * <pre>
   * Array of user IDs who have liked the image
   * </pre>
   *
   * <code>repeated string users = 6;</code>
   */
  java.lang.String getUsers6(int index);
  /**
   * <pre>
   * Array of user IDs who have liked the image
   * </pre>
   *
   * <code>repeated string users = 6;</code>
   */
  com.google.protobuf.ByteString
      getUsers6Bytes(int index);
}
