// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_service.proto

package com.instagram_clone.image_service;

/**
 * Protobuf type {@code Image.Image}
 */
public  final class Image extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Image.Image)
    ImageOrBuilder {
  // Use Image.newBuilder() to construct.
  private Image(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Image() {
    id_ = "";
    mimeType_ = "";
    width_ = 0;
    height_ = 0;
    userId_ = "";
    caption_ = "";
    createdAt_ = "";
    userTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    hashTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    likes_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private Image(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            id_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            mimeType_ = s;
            break;
          }
          case 24: {

            width_ = input.readInt32();
            break;
          }
          case 32: {

            height_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            userId_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            caption_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            createdAt_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              userTags_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000080;
            }
            userTags_.add(s);
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
              hashTags_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000100;
            }
            hashTags_.add(s);
            break;
          }
          case 80: {

            likes_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
        userTags_ = userTags_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000100) == 0x00000100)) {
        hashTags_ = hashTags_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.instagram_clone.image_service.ImageService.internal_static_Image_Image_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.instagram_clone.image_service.ImageService.internal_static_Image_Image_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.instagram_clone.image_service.Image.class, com.instagram_clone.image_service.Image.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object id_;
  /**
   * <pre>
   * ID of the image
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ID of the image
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MIME_TYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object mimeType_;
  /**
   * <pre>
   * Mime type of the image, e.g. img/png or img/jpeg
   * </pre>
   *
   * <code>string mime_type = 2;</code>
   */
  public java.lang.String getMimeType() {
    java.lang.Object ref = mimeType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mimeType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Mime type of the image, e.g. img/png or img/jpeg
   * </pre>
   *
   * <code>string mime_type = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMimeTypeBytes() {
    java.lang.Object ref = mimeType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mimeType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WIDTH_FIELD_NUMBER = 3;
  private int width_;
  /**
   * <pre>
   * Width in pixels
   * </pre>
   *
   * <code>int32 width = 3;</code>
   */
  public int getWidth() {
    return width_;
  }

  public static final int HEIGHT_FIELD_NUMBER = 4;
  private int height_;
  /**
   * <pre>
   * Height in pixels
   * </pre>
   *
   * <code>int32 height = 4;</code>
   */
  public int getHeight() {
    return height_;
  }

  public static final int USER_ID_FIELD_NUMBER = 5;
  private volatile java.lang.Object userId_;
  /**
   * <pre>
   * Image poster ID
   * </pre>
   *
   * <code>string user_id = 5;</code>
   */
  public java.lang.String getUserId() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      userId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Image poster ID
   * </pre>
   *
   * <code>string user_id = 5;</code>
   */
  public com.google.protobuf.ByteString
      getUserIdBytes() {
    java.lang.Object ref = userId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      userId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAPTION_FIELD_NUMBER = 6;
  private volatile java.lang.Object caption_;
  /**
   * <pre>
   * Image caption
   * </pre>
   *
   * <code>string caption = 6;</code>
   */
  public java.lang.String getCaption() {
    java.lang.Object ref = caption_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      caption_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Image caption
   * </pre>
   *
   * <code>string caption = 6;</code>
   */
  public com.google.protobuf.ByteString
      getCaptionBytes() {
    java.lang.Object ref = caption_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      caption_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATED_AT_FIELD_NUMBER = 7;
  private volatile java.lang.Object createdAt_;
  /**
   * <pre>
   * Created at timestamp
   * </pre>
   *
   * <code>string created_at = 7;</code>
   */
  public java.lang.String getCreatedAt() {
    java.lang.Object ref = createdAt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createdAt_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Created at timestamp
   * </pre>
   *
   * <code>string created_at = 7;</code>
   */
  public com.google.protobuf.ByteString
      getCreatedAtBytes() {
    java.lang.Object ref = createdAt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createdAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USER_TAGS_FIELD_NUMBER = 8;
  private com.google.protobuf.LazyStringList userTags_;
  /**
   * <pre>
   * Users marked into the image caption
   * </pre>
   *
   * <code>repeated string user_tags = 8;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getUserTagsList() {
    return userTags_;
  }
  /**
   * <pre>
   * Users marked into the image caption
   * </pre>
   *
   * <code>repeated string user_tags = 8;</code>
   */
  public int getUserTagsCount() {
    return userTags_.size();
  }
  /**
   * <pre>
   * Users marked into the image caption
   * </pre>
   *
   * <code>repeated string user_tags = 8;</code>
   */
  public java.lang.String getUserTags(int index) {
    return userTags_.get(index);
  }
  /**
   * <pre>
   * Users marked into the image caption
   * </pre>
   *
   * <code>repeated string user_tags = 8;</code>
   */
  public com.google.protobuf.ByteString
      getUserTagsBytes(int index) {
    return userTags_.getByteString(index);
  }

  public static final int HASH_TAGS_FIELD_NUMBER = 9;
  private com.google.protobuf.LazyStringList hashTags_;
  /**
   * <pre>
   * Hash tags marked into the image caption
   * </pre>
   *
   * <code>repeated string hash_tags = 9;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getHashTagsList() {
    return hashTags_;
  }
  /**
   * <pre>
   * Hash tags marked into the image caption
   * </pre>
   *
   * <code>repeated string hash_tags = 9;</code>
   */
  public int getHashTagsCount() {
    return hashTags_.size();
  }
  /**
   * <pre>
   * Hash tags marked into the image caption
   * </pre>
   *
   * <code>repeated string hash_tags = 9;</code>
   */
  public java.lang.String getHashTags(int index) {
    return hashTags_.get(index);
  }
  /**
   * <pre>
   * Hash tags marked into the image caption
   * </pre>
   *
   * <code>repeated string hash_tags = 9;</code>
   */
  public com.google.protobuf.ByteString
      getHashTagsBytes(int index) {
    return hashTags_.getByteString(index);
  }

  public static final int LIKES_FIELD_NUMBER = 10;
  private int likes_;
  /**
   * <pre>
   * Like counter
   * </pre>
   *
   * <code>int32 likes = 10;</code>
   */
  public int getLikes() {
    return likes_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
    }
    if (!getMimeTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mimeType_);
    }
    if (width_ != 0) {
      output.writeInt32(3, width_);
    }
    if (height_ != 0) {
      output.writeInt32(4, height_);
    }
    if (!getUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userId_);
    }
    if (!getCaptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, caption_);
    }
    if (!getCreatedAtBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, createdAt_);
    }
    for (int i = 0; i < userTags_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, userTags_.getRaw(i));
    }
    for (int i = 0; i < hashTags_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, hashTags_.getRaw(i));
    }
    if (likes_ != 0) {
      output.writeInt32(10, likes_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
    }
    if (!getMimeTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mimeType_);
    }
    if (width_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, width_);
    }
    if (height_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, height_);
    }
    if (!getUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userId_);
    }
    if (!getCaptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, caption_);
    }
    if (!getCreatedAtBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, createdAt_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < userTags_.size(); i++) {
        dataSize += computeStringSizeNoTag(userTags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getUserTagsList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < hashTags_.size(); i++) {
        dataSize += computeStringSizeNoTag(hashTags_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getHashTagsList().size();
    }
    if (likes_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, likes_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.instagram_clone.image_service.Image)) {
      return super.equals(obj);
    }
    com.instagram_clone.image_service.Image other = (com.instagram_clone.image_service.Image) obj;

    boolean result = true;
    result = result && getId()
        .equals(other.getId());
    result = result && getMimeType()
        .equals(other.getMimeType());
    result = result && (getWidth()
        == other.getWidth());
    result = result && (getHeight()
        == other.getHeight());
    result = result && getUserId()
        .equals(other.getUserId());
    result = result && getCaption()
        .equals(other.getCaption());
    result = result && getCreatedAt()
        .equals(other.getCreatedAt());
    result = result && getUserTagsList()
        .equals(other.getUserTagsList());
    result = result && getHashTagsList()
        .equals(other.getHashTagsList());
    result = result && (getLikes()
        == other.getLikes());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId().hashCode();
    hash = (37 * hash) + MIME_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getMimeType().hashCode();
    hash = (37 * hash) + WIDTH_FIELD_NUMBER;
    hash = (53 * hash) + getWidth();
    hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
    hash = (53 * hash) + getHeight();
    hash = (37 * hash) + USER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getUserId().hashCode();
    hash = (37 * hash) + CAPTION_FIELD_NUMBER;
    hash = (53 * hash) + getCaption().hashCode();
    hash = (37 * hash) + CREATED_AT_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedAt().hashCode();
    if (getUserTagsCount() > 0) {
      hash = (37 * hash) + USER_TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getUserTagsList().hashCode();
    }
    if (getHashTagsCount() > 0) {
      hash = (37 * hash) + HASH_TAGS_FIELD_NUMBER;
      hash = (53 * hash) + getHashTagsList().hashCode();
    }
    hash = (37 * hash) + LIKES_FIELD_NUMBER;
    hash = (53 * hash) + getLikes();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.instagram_clone.image_service.Image parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.instagram_clone.image_service.Image parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.instagram_clone.image_service.Image parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.instagram_clone.image_service.Image parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.instagram_clone.image_service.Image parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.instagram_clone.image_service.Image parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.instagram_clone.image_service.Image parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.instagram_clone.image_service.Image parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.instagram_clone.image_service.Image parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.instagram_clone.image_service.Image parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.instagram_clone.image_service.Image parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.instagram_clone.image_service.Image parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.instagram_clone.image_service.Image prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Image.Image}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Image.Image)
      com.instagram_clone.image_service.ImageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.instagram_clone.image_service.ImageService.internal_static_Image_Image_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.instagram_clone.image_service.ImageService.internal_static_Image_Image_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.instagram_clone.image_service.Image.class, com.instagram_clone.image_service.Image.Builder.class);
    }

    // Construct using com.instagram_clone.image_service.Image.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = "";

      mimeType_ = "";

      width_ = 0;

      height_ = 0;

      userId_ = "";

      caption_ = "";

      createdAt_ = "";

      userTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000080);
      hashTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000100);
      likes_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.instagram_clone.image_service.ImageService.internal_static_Image_Image_descriptor;
    }

    public com.instagram_clone.image_service.Image getDefaultInstanceForType() {
      return com.instagram_clone.image_service.Image.getDefaultInstance();
    }

    public com.instagram_clone.image_service.Image build() {
      com.instagram_clone.image_service.Image result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.instagram_clone.image_service.Image buildPartial() {
      com.instagram_clone.image_service.Image result = new com.instagram_clone.image_service.Image(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.mimeType_ = mimeType_;
      result.width_ = width_;
      result.height_ = height_;
      result.userId_ = userId_;
      result.caption_ = caption_;
      result.createdAt_ = createdAt_;
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        userTags_ = userTags_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000080);
      }
      result.userTags_ = userTags_;
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        hashTags_ = hashTags_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000100);
      }
      result.hashTags_ = hashTags_;
      result.likes_ = likes_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.instagram_clone.image_service.Image) {
        return mergeFrom((com.instagram_clone.image_service.Image)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.instagram_clone.image_service.Image other) {
      if (other == com.instagram_clone.image_service.Image.getDefaultInstance()) return this;
      if (!other.getId().isEmpty()) {
        id_ = other.id_;
        onChanged();
      }
      if (!other.getMimeType().isEmpty()) {
        mimeType_ = other.mimeType_;
        onChanged();
      }
      if (other.getWidth() != 0) {
        setWidth(other.getWidth());
      }
      if (other.getHeight() != 0) {
        setHeight(other.getHeight());
      }
      if (!other.getUserId().isEmpty()) {
        userId_ = other.userId_;
        onChanged();
      }
      if (!other.getCaption().isEmpty()) {
        caption_ = other.caption_;
        onChanged();
      }
      if (!other.getCreatedAt().isEmpty()) {
        createdAt_ = other.createdAt_;
        onChanged();
      }
      if (!other.userTags_.isEmpty()) {
        if (userTags_.isEmpty()) {
          userTags_ = other.userTags_;
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          ensureUserTagsIsMutable();
          userTags_.addAll(other.userTags_);
        }
        onChanged();
      }
      if (!other.hashTags_.isEmpty()) {
        if (hashTags_.isEmpty()) {
          hashTags_ = other.hashTags_;
          bitField0_ = (bitField0_ & ~0x00000100);
        } else {
          ensureHashTagsIsMutable();
          hashTags_.addAll(other.hashTags_);
        }
        onChanged();
      }
      if (other.getLikes() != 0) {
        setLikes(other.getLikes());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.instagram_clone.image_service.Image parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.instagram_clone.image_service.Image) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <pre>
     * ID of the image
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ID of the image
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ID of the image
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID of the image
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = getDefaultInstance().getId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID of the image
     * </pre>
     *
     * <code>string id = 1;</code>
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      id_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mimeType_ = "";
    /**
     * <pre>
     * Mime type of the image, e.g. img/png or img/jpeg
     * </pre>
     *
     * <code>string mime_type = 2;</code>
     */
    public java.lang.String getMimeType() {
      java.lang.Object ref = mimeType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mimeType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Mime type of the image, e.g. img/png or img/jpeg
     * </pre>
     *
     * <code>string mime_type = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMimeTypeBytes() {
      java.lang.Object ref = mimeType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mimeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Mime type of the image, e.g. img/png or img/jpeg
     * </pre>
     *
     * <code>string mime_type = 2;</code>
     */
    public Builder setMimeType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mimeType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Mime type of the image, e.g. img/png or img/jpeg
     * </pre>
     *
     * <code>string mime_type = 2;</code>
     */
    public Builder clearMimeType() {
      
      mimeType_ = getDefaultInstance().getMimeType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Mime type of the image, e.g. img/png or img/jpeg
     * </pre>
     *
     * <code>string mime_type = 2;</code>
     */
    public Builder setMimeTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mimeType_ = value;
      onChanged();
      return this;
    }

    private int width_ ;
    /**
     * <pre>
     * Width in pixels
     * </pre>
     *
     * <code>int32 width = 3;</code>
     */
    public int getWidth() {
      return width_;
    }
    /**
     * <pre>
     * Width in pixels
     * </pre>
     *
     * <code>int32 width = 3;</code>
     */
    public Builder setWidth(int value) {
      
      width_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Width in pixels
     * </pre>
     *
     * <code>int32 width = 3;</code>
     */
    public Builder clearWidth() {
      
      width_ = 0;
      onChanged();
      return this;
    }

    private int height_ ;
    /**
     * <pre>
     * Height in pixels
     * </pre>
     *
     * <code>int32 height = 4;</code>
     */
    public int getHeight() {
      return height_;
    }
    /**
     * <pre>
     * Height in pixels
     * </pre>
     *
     * <code>int32 height = 4;</code>
     */
    public Builder setHeight(int value) {
      
      height_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Height in pixels
     * </pre>
     *
     * <code>int32 height = 4;</code>
     */
    public Builder clearHeight() {
      
      height_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object userId_ = "";
    /**
     * <pre>
     * Image poster ID
     * </pre>
     *
     * <code>string user_id = 5;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Image poster ID
     * </pre>
     *
     * <code>string user_id = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Image poster ID
     * </pre>
     *
     * <code>string user_id = 5;</code>
     */
    public Builder setUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Image poster ID
     * </pre>
     *
     * <code>string user_id = 5;</code>
     */
    public Builder clearUserId() {
      
      userId_ = getDefaultInstance().getUserId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Image poster ID
     * </pre>
     *
     * <code>string user_id = 5;</code>
     */
    public Builder setUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      userId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object caption_ = "";
    /**
     * <pre>
     * Image caption
     * </pre>
     *
     * <code>string caption = 6;</code>
     */
    public java.lang.String getCaption() {
      java.lang.Object ref = caption_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        caption_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Image caption
     * </pre>
     *
     * <code>string caption = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCaptionBytes() {
      java.lang.Object ref = caption_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        caption_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Image caption
     * </pre>
     *
     * <code>string caption = 6;</code>
     */
    public Builder setCaption(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      caption_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Image caption
     * </pre>
     *
     * <code>string caption = 6;</code>
     */
    public Builder clearCaption() {
      
      caption_ = getDefaultInstance().getCaption();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Image caption
     * </pre>
     *
     * <code>string caption = 6;</code>
     */
    public Builder setCaptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      caption_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object createdAt_ = "";
    /**
     * <pre>
     * Created at timestamp
     * </pre>
     *
     * <code>string created_at = 7;</code>
     */
    public java.lang.String getCreatedAt() {
      java.lang.Object ref = createdAt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdAt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Created at timestamp
     * </pre>
     *
     * <code>string created_at = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCreatedAtBytes() {
      java.lang.Object ref = createdAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Created at timestamp
     * </pre>
     *
     * <code>string created_at = 7;</code>
     */
    public Builder setCreatedAt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createdAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Created at timestamp
     * </pre>
     *
     * <code>string created_at = 7;</code>
     */
    public Builder clearCreatedAt() {
      
      createdAt_ = getDefaultInstance().getCreatedAt();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Created at timestamp
     * </pre>
     *
     * <code>string created_at = 7;</code>
     */
    public Builder setCreatedAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createdAt_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList userTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureUserTagsIsMutable() {
      if (!((bitField0_ & 0x00000080) == 0x00000080)) {
        userTags_ = new com.google.protobuf.LazyStringArrayList(userTags_);
        bitField0_ |= 0x00000080;
       }
    }
    /**
     * <pre>
     * Users marked into the image caption
     * </pre>
     *
     * <code>repeated string user_tags = 8;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getUserTagsList() {
      return userTags_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Users marked into the image caption
     * </pre>
     *
     * <code>repeated string user_tags = 8;</code>
     */
    public int getUserTagsCount() {
      return userTags_.size();
    }
    /**
     * <pre>
     * Users marked into the image caption
     * </pre>
     *
     * <code>repeated string user_tags = 8;</code>
     */
    public java.lang.String getUserTags(int index) {
      return userTags_.get(index);
    }
    /**
     * <pre>
     * Users marked into the image caption
     * </pre>
     *
     * <code>repeated string user_tags = 8;</code>
     */
    public com.google.protobuf.ByteString
        getUserTagsBytes(int index) {
      return userTags_.getByteString(index);
    }
    /**
     * <pre>
     * Users marked into the image caption
     * </pre>
     *
     * <code>repeated string user_tags = 8;</code>
     */
    public Builder setUserTags(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUserTagsIsMutable();
      userTags_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Users marked into the image caption
     * </pre>
     *
     * <code>repeated string user_tags = 8;</code>
     */
    public Builder addUserTags(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureUserTagsIsMutable();
      userTags_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Users marked into the image caption
     * </pre>
     *
     * <code>repeated string user_tags = 8;</code>
     */
    public Builder addAllUserTags(
        java.lang.Iterable<java.lang.String> values) {
      ensureUserTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, userTags_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Users marked into the image caption
     * </pre>
     *
     * <code>repeated string user_tags = 8;</code>
     */
    public Builder clearUserTags() {
      userTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Users marked into the image caption
     * </pre>
     *
     * <code>repeated string user_tags = 8;</code>
     */
    public Builder addUserTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureUserTagsIsMutable();
      userTags_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList hashTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureHashTagsIsMutable() {
      if (!((bitField0_ & 0x00000100) == 0x00000100)) {
        hashTags_ = new com.google.protobuf.LazyStringArrayList(hashTags_);
        bitField0_ |= 0x00000100;
       }
    }
    /**
     * <pre>
     * Hash tags marked into the image caption
     * </pre>
     *
     * <code>repeated string hash_tags = 9;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getHashTagsList() {
      return hashTags_.getUnmodifiableView();
    }
    /**
     * <pre>
     * Hash tags marked into the image caption
     * </pre>
     *
     * <code>repeated string hash_tags = 9;</code>
     */
    public int getHashTagsCount() {
      return hashTags_.size();
    }
    /**
     * <pre>
     * Hash tags marked into the image caption
     * </pre>
     *
     * <code>repeated string hash_tags = 9;</code>
     */
    public java.lang.String getHashTags(int index) {
      return hashTags_.get(index);
    }
    /**
     * <pre>
     * Hash tags marked into the image caption
     * </pre>
     *
     * <code>repeated string hash_tags = 9;</code>
     */
    public com.google.protobuf.ByteString
        getHashTagsBytes(int index) {
      return hashTags_.getByteString(index);
    }
    /**
     * <pre>
     * Hash tags marked into the image caption
     * </pre>
     *
     * <code>repeated string hash_tags = 9;</code>
     */
    public Builder setHashTags(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureHashTagsIsMutable();
      hashTags_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Hash tags marked into the image caption
     * </pre>
     *
     * <code>repeated string hash_tags = 9;</code>
     */
    public Builder addHashTags(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureHashTagsIsMutable();
      hashTags_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Hash tags marked into the image caption
     * </pre>
     *
     * <code>repeated string hash_tags = 9;</code>
     */
    public Builder addAllHashTags(
        java.lang.Iterable<java.lang.String> values) {
      ensureHashTagsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, hashTags_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Hash tags marked into the image caption
     * </pre>
     *
     * <code>repeated string hash_tags = 9;</code>
     */
    public Builder clearHashTags() {
      hashTags_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000100);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Hash tags marked into the image caption
     * </pre>
     *
     * <code>repeated string hash_tags = 9;</code>
     */
    public Builder addHashTagsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureHashTagsIsMutable();
      hashTags_.add(value);
      onChanged();
      return this;
    }

    private int likes_ ;
    /**
     * <pre>
     * Like counter
     * </pre>
     *
     * <code>int32 likes = 10;</code>
     */
    public int getLikes() {
      return likes_;
    }
    /**
     * <pre>
     * Like counter
     * </pre>
     *
     * <code>int32 likes = 10;</code>
     */
    public Builder setLikes(int value) {
      
      likes_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Like counter
     * </pre>
     *
     * <code>int32 likes = 10;</code>
     */
    public Builder clearLikes() {
      
      likes_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:Image.Image)
  }

  // @@protoc_insertion_point(class_scope:Image.Image)
  private static final com.instagram_clone.image_service.Image DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.instagram_clone.image_service.Image();
  }

  public static com.instagram_clone.image_service.Image getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Image>
      PARSER = new com.google.protobuf.AbstractParser<Image>() {
    public Image parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new Image(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Image> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Image> getParserForType() {
    return PARSER;
  }

  public com.instagram_clone.image_service.Image getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

