// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_service.proto

package com.instagram_clone.image_service;

/**
 * Protobuf enum {@code Image.ImageType}
 */
public enum ImageType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>PNG = 0;</code>
   */
  PNG(0),
  /**
   * <code>JPG = 1;</code>
   */
  JPG(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>PNG = 0;</code>
   */
  public static final int PNG_VALUE = 0;
  /**
   * <code>JPG = 1;</code>
   */
  public static final int JPG_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ImageType valueOf(int value) {
    return forNumber(value);
  }

  public static ImageType forNumber(int value) {
    switch (value) {
      case 0: return PNG;
      case 1: return JPG;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ImageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ImageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ImageType>() {
          public ImageType findValueByNumber(int number) {
            return ImageType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.instagram_clone.image_service.ImageService.getDescriptor().getEnumTypes().get(0);
  }

  private static final ImageType[] VALUES = values();

  public static ImageType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ImageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Image.ImageType)
}

