// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_service.proto

package com.instagram_clone.image_service;

public interface LikeImageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Image.LikeImageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string image_id = 1;</code>
   */
  java.lang.String getImageId();
  /**
   * <code>string image_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getImageIdBytes();

  /**
   * <code>string user_id = 2;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>bool unlike = 3;</code>
   */
  boolean getUnlike();
}
