// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_service.proto

package com.instagram_clone.image_service;

public interface LikeImageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Image.LikeImageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Image.LikeImageResponseStatus status = 1;</code>
   */
  int getStatusValue();
  /**
   * <code>.Image.LikeImageResponseStatus status = 1;</code>
   */
  com.instagram_clone.image_service.LikeImageResponseStatus getStatus();
}
