// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_service.proto

package com.instagram_clone.image_service;

public interface SearchImagesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Image.SearchImagesRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hash_tag = 1;</code>
   */
  java.lang.String getHashTag();
  /**
   * <code>string hash_tag = 1;</code>
   */
  com.google.protobuf.ByteString
      getHashTagBytes();

  /**
   * <code>string user_tag = 2;</code>
   */
  java.lang.String getUserTag();
  /**
   * <code>string user_tag = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserTagBytes();

  public com.instagram_clone.image_service.SearchImagesRequest.SearchCase getSearchCase();
}
