// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comment_service.proto

package com.instagram_clone.comment_service;

public interface GetCommentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Comment.GetCommentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string commentId = 1;</code>
   */
  java.lang.String getCommentId();
  /**
   * <code>string commentId = 1;</code>
   */
  com.google.protobuf.ByteString
      getCommentIdBytes();
}
