// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comment_service.proto

package com.instagram_clone.comment_service;

/**
 * Protobuf enum {@code Comment.CreateCommentErrorStatus}
 */
public enum CreateCommentErrorStatus
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CREATE_SERVER_ERROR = 0;</code>
   */
  CREATE_SERVER_ERROR(0),
  /**
   * <code>CREATE_INVALID_PARAMETER = 1;</code>
   */
  CREATE_INVALID_PARAMETER(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CREATE_SERVER_ERROR = 0;</code>
   */
  public static final int CREATE_SERVER_ERROR_VALUE = 0;
  /**
   * <code>CREATE_INVALID_PARAMETER = 1;</code>
   */
  public static final int CREATE_INVALID_PARAMETER_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CreateCommentErrorStatus valueOf(int value) {
    return forNumber(value);
  }

  public static CreateCommentErrorStatus forNumber(int value) {
    switch (value) {
      case 0: return CREATE_SERVER_ERROR;
      case 1: return CREATE_INVALID_PARAMETER;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CreateCommentErrorStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CreateCommentErrorStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CreateCommentErrorStatus>() {
          public CreateCommentErrorStatus findValueByNumber(int number) {
            return CreateCommentErrorStatus.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.instagram_clone.comment_service.CommentService.getDescriptor().getEnumTypes().get(3);
  }

  private static final CreateCommentErrorStatus[] VALUES = values();

  public static CreateCommentErrorStatus valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private CreateCommentErrorStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:Comment.CreateCommentErrorStatus)
}

