// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comment_service.proto

package com.instagram_clone.comment_service;

public interface DeleteCommentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Comment.DeleteCommentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string commentId = 1;</code>
   */
  java.lang.String getCommentId();
  /**
   * <code>string commentId = 1;</code>
   */
  com.google.protobuf.ByteString
      getCommentIdBytes();

  /**
   * <code>.Comment.DeleteCommentErrorStatus error = 2;</code>
   */
  int getErrorValue();
  /**
   * <code>.Comment.DeleteCommentErrorStatus error = 2;</code>
   */
  com.instagram_clone.comment_service.DeleteCommentErrorStatus getError();

  public com.instagram_clone.comment_service.DeleteCommentResponse.StatusCase getStatusCase();
}
