// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comment_service.proto

package com.instagram_clone.comment_service;

public interface GetCommentResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Comment.GetCommentResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Comment.Comment comment = 1;</code>
   */
  com.instagram_clone.comment_service.Comment getComment();
  /**
   * <code>.Comment.Comment comment = 1;</code>
   */
  com.instagram_clone.comment_service.CommentOrBuilder getCommentOrBuilder();

  /**
   * <code>.Comment.GetCommentErrorStatus error = 2;</code>
   */
  int getErrorValue();
  /**
   * <code>.Comment.GetCommentErrorStatus error = 2;</code>
   */
  com.instagram_clone.comment_service.GetCommentErrorStatus getError();

  public com.instagram_clone.comment_service.GetCommentResponse.StatusCase getStatusCase();
}
