// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comment_service.proto

package com.instagram_clone.comment_service;

public interface GetCommentsByTagResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Comment.GetCommentsByTagResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Comment.CommentList comments = 1;</code>
   */
  com.instagram_clone.comment_service.CommentList getComments();
  /**
   * <code>.Comment.CommentList comments = 1;</code>
   */
  com.instagram_clone.comment_service.CommentListOrBuilder getCommentsOrBuilder();

  /**
   * <code>.Comment.GetCommentsByTagErrorStatus error = 2;</code>
   */
  int getErrorValue();
  /**
   * <code>.Comment.GetCommentsByTagErrorStatus error = 2;</code>
   */
  com.instagram_clone.comment_service.GetCommentsByTagErrorStatus getError();

  public com.instagram_clone.comment_service.GetCommentsByTagResponse.StatusCase getStatusCase();
}
