// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: comment_service.proto

package com.instagram_clone.comment_service;

public interface PagedCommentListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Comment.PagedCommentList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Comment.Comment comments = 1;</code>
   */
  java.util.List<com.instagram_clone.comment_service.Comment> 
      getCommentsList();
  /**
   * <code>repeated .Comment.Comment comments = 1;</code>
   */
  com.instagram_clone.comment_service.Comment getComments(int index);
  /**
   * <code>repeated .Comment.Comment comments = 1;</code>
   */
  int getCommentsCount();
  /**
   * <code>repeated .Comment.Comment comments = 1;</code>
   */
  java.util.List<? extends com.instagram_clone.comment_service.CommentOrBuilder> 
      getCommentsOrBuilderList();
  /**
   * <code>repeated .Comment.Comment comments = 1;</code>
   */
  com.instagram_clone.comment_service.CommentOrBuilder getCommentsOrBuilder(
      int index);

  /**
   * <code>int32 page = 2;</code>
   */
  int getPage();

  /**
   * <code>int32 totalCount = 3;</code>
   */
  int getTotalCount();

  /**
   * <code>int32 count = 4;</code>
   */
  int getCount();
}
