FROM python:3.7-alpine

# Dependencies for grpc and postgresql
RUN apk add --no-cache \
    gcc \
    linux-headers \
    make \
    musl-dev \
    python-dev \
    g++ \
    postgresql-libs \
    postgresql-dev

WORKDIR /src

COPY requirements.txt ./

RUN pip install -r requirements.txt

CMD [ "python", "-u", "server.py" ]
